Repository jHelsing/Heartbeat, pull requests merged in 2018-04, with the labels that each got.

#13 Initial Firebase setup
  package.json
  src/app/app.module.ts
  src/config/firebase.config.ts
  src/models/user.ts
  src/pages/home/home.html
  src/pages/home/home.ts
  tslint.json
Labels: enhancement

#20 Tidy up patient code
  src/app/app.component.ts
  src/pages/add-patient/add-patient.html
  src/pages/add-patient/add-patient.scss
  src/pages/add-patient/add-patient.ts
  src/pages/home/home.html
  src/pages/patient-detail/patient-detail.html
  src/pages/patient-detail/patient-detail.ts
  src/pages/patient/patient.html
  src/pages/patient/patient.ts
  src/pages/update-patient/update-patient.html
  src/pages/update-patient/update-patient.scss
  src/pages/update-patient/update-patient.ts
Labels: refactored code

#17 Create doctor
  src/app/app.module.ts
  src/models/doctor.ts
  src/models/specialities.ts
  src/pages/doctorRegistration/doctorRegistration.html
  src/pages/doctorRegistration/doctorRegistration.scss
  src/pages/doctorRegistration/doctorRegistration.ts
  src/pages/home/home.html
  src/pages/home/home.ts
Labels: new feature

#24 doctor refactored
  src/app/app.module.ts
  src/models/doctor.ts
  src/models/specialities.ts
  src/models/speciality.ts
  src/pages/add-doctor/add-doctor.html
  src/pages/add-doctor/add-doctor.scss
  src/pages/add-doctor/add-doctor.ts
  src/pages/doctorRegistration/doctorRegistration.html
  src/pages/doctorRegistration/doctorRegistration.ts
  src/pages/home/home.ts
  src/providers/doctor/doctor.ts
  src/providers/room/room.ts
  src/providers/speciality/speciality.ts
Labels: refactored code

#28 Patient details and comments
  src/app/app.component.ts
  src/app/app.module.ts
  src/components/add-comment/add-comment.html
  src/components/add-comment/add-comment.scss
  src/components/add-comment/add-comment.ts
  src/components/components.module.ts
  src/models/comment.ts
  src/pages/add-patient/add-patient.ts
  src/pages/admin-tabs/admin-tabs.ts
  src/pages/home/home.ts
  src/pages/patient-detail/patient-detail.html
  src/pages/patient-detail/patient-detail.ts
  src/pages/patient-list/patient-list.html
  src/pages/patient-list/patient-list.module.ts
  src/pages/patient-list/patient-list.scss
  src/pages/patient-list/patient-list.ts
  src/pages/patient/patient.scss
  src/pages/update-patient/update-patient.ts
  src/providers/comment/comment.ts
  src/providers/storage/storage.ts
Labels: new feature, updated design
