Repository jHelsing/Heartbeat, pull requests merged in 2018-05, with the labels that each got.

#37 Distinguish comment categories by color
  src/pages/patient-detail/patient-detail.html
  src/pages/patient-detail/patient-detail.scss
  src/theme/variables.scss
Labels: feature improvement

#34 Add patient severity
  src/components/add-comment/add-comment.html
  src/components/add-comment/add-comment.ts
  src/models/comment.ts
  src/models/patient.ts
  src/pages/add-patient/add-patient.ts
  src/pages/admin-tabs/admin-tabs.html
  src/pages/login/login.ts
  src/pages/patient-detail/patient-detail.html
  src/pages/patient-detail/patient-detail.scss
  src/pages/patient-detail/patient-detail.ts
  src/pages/patient-list/patient-list.html
  src/pages/patient-list/patient-list.ts
  src/providers/comment/comment.ts
  src/providers/patient/patient.ts
Labels: new feature

#39 Update theme colors for badges
  src/pages/patient-list/patient-list.html
  src/theme/variables.scss
Labels: updated design

#36 Add url as admin
  package.json
  src/models/doctor.ts
  src/models/nurse.ts
  src/pages/add-doctor/add-doctor.html
  src/pages/add-nurse/add-nurse.html
  src/pages/doctor-detail/doctor-detail.html
  src/pages/doctor-list/doctor-list.html
  src/pages/nurse-list/nurse-list.html
  src/pages/nurse-list/nurse-list.ts
Labels: new feature

#35 Support for image in diagnosis
  src/components/add-comment/add-comment.html
  src/models/comment.ts
  src/providers/comment/comment.ts
Labels: new feature

#38 Restrict add patient
  config.xml
  package-lock.json
  package.json
  src/app/app.module.ts
  src/components/add-comment/add-comment.ts
  src/components/popover/popover.html
  src/components/popover/popover.scss
  src/components/popover/popover.ts
  src/models/administrator.ts
  src/pages/admin-tabs/admin-tabs.html
  src/pages/doctor-list/doctor-list.ts
  src/pages/login/login.ts
  src/pages/patient-detail/patient-detail.ts
  src/pages/patient-list/patient-list.html
  src/pages/patient-list/patient-list.ts
  src/providers/patient/patient.ts
Labels: feature improvement, new feature

#40 Add credentials on adding doctor/nurse
  src/models/doctor.ts
  src/models/nurse.ts
  src/pages/add-doctor/add-doctor.html
  src/pages/add-doctor/add-doctor.ts
  src/pages/add-nurse/add-nurse.html
  src/pages/add-nurse/add-nurse.ts
  src/providers/login/login.ts
Labels: new feature
